### ISSUE TITLE
Example for how to use with multiple PubSub endpoints

### ISSUE THREAD

**Issue by simenandre** [simenandre/pubsub-http-handler#148]
I'm thinking mainly about the fastify-plugin, but we should probably provide examples/guides of how you can have multiple PubSub endpoints.

For the `createPubSubServer`, I think we shouldn't introduce the ability to have multiple PubSub endpoints. Users should in this case use Fastify. `createPubSubServer` are meant to be a super-easy way to get a PubSub handler up and running, I consider multiple endpoints a more in-depth implementation than that.

- [ ] Do research on how other fastify-plugins do multiple endpoints (multiple fastify.register or append something else?)

**Comment by thced** [comment]
This is how I implemented it:
```javascript
module.exports = (app, opts, done) => {
  app.decorateRequest(...);

  const routes = [
    {
      path: '/path-x',
      handler: async ({ message, data, log }) => {
        ...
      },
    },
    {
      path: '/path-y',
      handler: async ({ message, data, log }) => {
        ...
      },
    },
    {
      path: '/path-z',
      handler: async ({ message, data, log }) => {
        ...
      },
    },
  ];
  routes.forEach((route) => app.register(pubSubFastifyPlugin, route));
  done();
};
```

**Comment by simenandre** [comment]
This works fine for me! Closing :)
