### ISSUE TITLE
Add `createContext` function

### ISSUE THREAD

**Issue by runeh** [simenandre/pubsub-http-handler#179]
Related to brief discussion here https://github.com/cobraz/pubsub-http-handler/pull/178#issuecomment-1249431766 , we'll add a `createContext` function to the options. The result of calling that function is passed as the context to the handler. The `createContext` function will have access to the request object from the underlying http request, so it can inspect headers and so on.

**Comment by runeh** [comment]
Question about the semantics:

What should happen if the `createContext` call throws an error. I'm guessing  we then should invoke `onError`?

In that case we will not be able to pass in the context to onError, which sounds like it might be useful. Like if the context contains `userId`, and the `handler` fails, it'd be useful for `onError` to be able to log stuff in the context? Simplest is maybe to make the signature or `context` to be nullable, if passed to the `onError` handler.

Related issue, that might have consequences for this refactoring: What should happen if `onError` throws? For now, that is not dealt with, so a bug in onError will crash the request. That said, if there is a failing onError, there's not really anything we can do to recover, so makes sense that the error is propagated up and the message NACKed?

**Comment by runeh** [comment]
cc @SimenB @cobraz

**Comment by SimenB** [comment]
> The `createContext` function will have access to the request object from the underlying http request, so it can inspect headers and so on.

Should also be passed the `reply` object I think (to mirror e.g. `apollo-server`.

> What should happen if the `createContext` call throws an error. I'm guessing we then should invoke `onError`?

Depends on what `onError` does. Should it be called if a handler fails? In that case ot makes sense to call it here as well. If it's only called if things outside if the handler fails (like parsing the body), then it shouldn't be called.



> Related issue, that might have consequences for this refactoring: What should happen if `onError` throws?

Same as `apollo-server` methinks - just call your default error handler (probably just bubble up to express/fastify as unhandled)

**Comment by thced** [comment]
When can this be released? :)
